# Generated by Django 4.2.7 on 2023-11-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_apply',
            name='current_year',
        ),
        migrations.AddField(
            model_name='student_apply',
            name='current_date',
            field=models.DateField(auto_now=True),
        ),
    ]
