# Generated by Django 4.2.7 on 2023-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_apply_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_apply',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='puplished_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
