# Generated by Django 4.2.7 on 2023-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_apply_full_name_userprofile_puplished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_apply',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
