# Generated by Django 4.2.7 on 2023-11-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_apply_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shekh_mohafez',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shekh_tester',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student_apply',
            name='basic_info',
        ),
        migrations.RemoveField(
            model_name='student_apply',
            name='student_country',
        ),
        migrations.RemoveField(
            model_name='student_apply',
            name='student_shekh_mohafez',
        ),
        migrations.RemoveField(
            model_name='student_apply',
            name='student_shekh_tester',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Shekh_Mohafez',
        ),
        migrations.DeleteModel(
            name='Shekh_Tester',
        ),
        migrations.DeleteModel(
            name='Student_Apply',
        ),
    ]
